main: dev.kyriji.spigot.TritonCoreSpigot
name: TritonCoreSpigot
version: 1.0.0
depend: [TritonDependencies]
commands:
  test:
  playerdata:
  inventory:
  msg:
  reply:
  ignore:
  socialspy:
  ban:
  ipban:
  kick:
  mute:
  warn:
  unban:
  unmute:
  logs: